# Generated by Django 2.1.2 on 2019-04-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20190404_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='activities',
            field=models.CharField(max_length=350),
        ),
    ]
