# Generated by Django 2.1.2 on 2019-05-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20190513_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthours',
            options={'permissions': (('modify_admin_site', 'Can view, modify, add, or delete project hours'),), 'verbose_name': 'project hours entry', 'verbose_name_plural': 'project hours entries'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['user', 'priority'], 'permissions': (('time_user', 'Can modify, add, view, or delete todos'),)},
        ),
    ]
