# Generated by Django 2.1.2 on 2019-06-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20190516_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-start_time',), 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='projecthours',
            options={'verbose_name': 'project hours entry', 'verbose_name_plural': 'project hours entries'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['user', 'priority']},
        ),
    ]
