# Generated by Django 2.1.2 on 2019-06-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_auto_20190601_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'default_permissions': (), 'ordering': ('-start_time',), 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='projecthours',
            options={'default_permissions': (), 'verbose_name': 'project hours entry', 'verbose_name_plural': 'project hours entries'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'default_permissions': (), 'ordering': ['user', 'priority']},
        ),
    ]
