# Generated by Django 2.1.2 on 2020-08-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigiKeyAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=150)),
                ('access_token', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fields', models.CharField(choices=[('char1', 'Character 1'), ('char2', 'Character 2'), ('char3', 'Character 3'), ('char4', 'Character 4'), ('char5', 'Character 5'), ('char6', 'Character 6'), ('char7', 'Character 7'), ('char8', 'Character 8'), ('char9', 'Character 9'), ('char10', 'Character 10'), ('char11', 'Character 11'), ('char12', 'Character 12'), ('char13', 'Character 13'), ('char14', 'Character 14'), ('char15', 'Character 15'), ('char16', 'Character 16'), ('char17', 'Character 17'), ('char18', 'Character 18'), ('char19', 'Character 19'), ('char20', 'Character 20'), ('char21', 'Character 21'), ('char22', 'Character 22'), ('char23', 'Character 23'), ('char24', 'Character 24'), ('char25', 'Character 25'), ('char26', 'Character 26'), ('char27', 'Character 27'), ('char28', 'Character 28'), ('char29', 'Character 29'), ('char30', 'Character 30'), ('char31', 'Character 31'), ('char32', 'Character 32'), ('char33', 'Character 33'), ('char34', 'Character 34'), ('char35', 'Character 35')], max_length=50)),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or delete fields'),),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete locations'),),
            },
        ),
        migrations.CreateModel(
            name='LocationRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Location')),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or location relationships'),),
            },
        ),
        migrations.CreateModel(
            name='ManufacturerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or delete manufacturer relationships'),),
            },
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or delete manufacturing orders'),),
            },
        ),
        migrations.CreateModel(
            name='MOProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.ManufacturingOrder')),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or delete MO products'),),
            },
        ),
        migrations.CreateModel(
            name='MrpSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'permissions': (('mrp_user', 'Can access mrp site'), ('modify_admin_site', 'Can access admin site, do redirects'), ('time_user', 'Can clock in and out and handle todos'), ('time_supervisor', 'Can manage projects'), ('mrp_admin', 'Can view, add, modify, or delete digikeys')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engimusingPartNumber', models.CharField(editable=False, max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('char1', models.CharField(blank=True, max_length=200)),
                ('char2', models.CharField(blank=True, max_length=100)),
                ('char3', models.CharField(blank=True, max_length=100)),
                ('char4', models.CharField(blank=True, max_length=100)),
                ('char5', models.CharField(blank=True, max_length=100)),
                ('char6', models.CharField(blank=True, max_length=100)),
                ('char7', models.CharField(blank=True, max_length=100)),
                ('char8', models.CharField(blank=True, max_length=100)),
                ('char9', models.CharField(blank=True, max_length=100)),
                ('char10', models.CharField(blank=True, max_length=100)),
                ('char11', models.CharField(blank=True, max_length=100)),
                ('char12', models.CharField(blank=True, max_length=100)),
                ('char13', models.CharField(blank=True, max_length=100)),
                ('char14', models.CharField(blank=True, max_length=100)),
                ('char15', models.CharField(blank=True, max_length=100)),
                ('char16', models.CharField(blank=True, max_length=100)),
                ('char17', models.CharField(blank=True, max_length=100)),
                ('char18', models.CharField(blank=True, max_length=100)),
                ('char19', models.CharField(blank=True, max_length=100)),
                ('char20', models.CharField(blank=True, max_length=100)),
                ('char21', models.CharField(blank=True, max_length=100)),
                ('char22', models.CharField(blank=True, max_length=100)),
                ('char23', models.CharField(blank=True, max_length=100)),
                ('char24', models.CharField(blank=True, max_length=100)),
                ('char25', models.CharField(blank=True, max_length=100)),
                ('char26', models.CharField(blank=True, max_length=100)),
                ('char27', models.CharField(blank=True, max_length=100)),
                ('char28', models.CharField(blank=True, max_length=100)),
                ('char29', models.CharField(blank=True, max_length=100)),
                ('char30', models.CharField(blank=True, max_length=100)),
                ('char31', models.CharField(blank=True, max_length=100)),
                ('char32', models.CharField(blank=True, max_length=100)),
                ('char33', models.CharField(blank=True, max_length=100)),
                ('char34', models.CharField(blank=True, max_length=100)),
                ('char35', models.CharField(blank=True, max_length=100)),
                ('datasheet', models.FileField(blank=True, upload_to='documents/')),
                ('location', models.ManyToManyField(through='mrp_system.LocationRelationship', to='mrp_system.Location')),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or delete parts'),),
            },
        ),
        migrations.CreateModel(
            name='PartAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=1, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part')),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete part amounts'),),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engimusing_product_number', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete products'),),
            },
        ),
        migrations.CreateModel(
            name='ProductAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=1, null=True)),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_product', to='mrp_system.Product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='mrp_system.Product')),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete product amounts'),),
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Product')),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or delete product locations'),),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20)),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete purchase orders'),),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('item_number', models.IntegerField(default=0, editable=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.PurchaseOrder')),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete purchase order parts'),),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(max_length=4)),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete types'),),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('vendor_type', models.CharField(choices=[('manufacturer', 'manufacturer'), ('distributor', 'distributor')], default='manufacturer', max_length=12)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('web_address', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete vendors'),),
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='part',
            field=models.ManyToManyField(through='mrp_system.PurchaseOrderParts', to='mrp_system.Part'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='component_product',
            field=models.ManyToManyField(through='mrp_system.ProductAmount', to='mrp_system.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ManyToManyField(through='mrp_system.ProductLocation', to='mrp_system.Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='part',
            field=models.ManyToManyField(through='mrp_system.PartAmount', to='mrp_system.Part'),
        ),
        migrations.AddField(
            model_name='partamount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Product'),
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturer',
            field=models.ManyToManyField(through='mrp_system.ManufacturerRelationship', to='mrp_system.Vendor'),
        ),
        migrations.AddField(
            model_name='part',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='mrp_system.Type'),
        ),
        migrations.AddField(
            model_name='moproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Product'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='product',
            field=models.ManyToManyField(through='mrp_system.MOProduct', to='mrp_system.Product'),
        ),
        migrations.AddField(
            model_name='manufacturerrelationship',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'vendor_type': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Vendor'),
        ),
        migrations.AddField(
            model_name='manufacturerrelationship',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part'),
        ),
        migrations.AddField(
            model_name='locationrelationship',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part'),
        ),
        migrations.AddField(
            model_name='field',
            name='typePart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='mrp_system.Type'),
        ),
    ]
