# Generated by Django 2.1.2 on 2021-02-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='engimusingPartNumber',
            new_name='engimusing_part_number',
        ),
    ]
