# Generated by Django 2.1.2 on 2021-03-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0002_auto_20210226_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturerrelationship',
            old_name='partNumber',
            new_name='part_number',
        ),
    ]
