# Generated by Django 3.1 on 2021-06-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0003_auto_20210317_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='char10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char13',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char14',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char15',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char16',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char17',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char18',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char19',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char20',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char21',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char22',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char23',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char24',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char25',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char26',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char27',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char28',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char29',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char30',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char31',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char32',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char33',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char34',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char35',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='char9',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
