# Generated by Django 2.1.2 on 2019-05-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0083_auto_20190131_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'permissions': (('modify_admin_site', 'Can modify, add, view, or delete fields'),)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': (('mrp_user', 'Can modify, add, view, or delete locations'),)},
        ),
        migrations.AlterModelOptions(
            name='locationrelationship',
            options={'permissions': (('modify_admin_site', 'Can modify, add, view, or location relationships'),)},
        ),
        migrations.AlterModelOptions(
            name='manufacturerrelationship',
            options={'permissions': (('modify_admin_site', 'Can modify, add, view, or delete manufacturer relationships'),)},
        ),
        migrations.AlterModelOptions(
            name='manufacturingorder',
            options={'permissions': (('modify_admin_site', 'Can modify, add, view, or delete manufacturing orders'),)},
        ),
        migrations.AlterModelOptions(
            name='moproduct',
            options={'permissions': (('modify_admin_site', 'Can modify, add, view, or delete MO products'),)},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'permissions': (('modify_admin_site', 'Can modify, add, view, or delete parts'),)},
        ),
        migrations.AlterModelOptions(
            name='partamount',
            options={'permissions': (('mrp_user', 'Can modify, add, view, or delete part amounts'),)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('mrp_user', 'Can modify, add, view, or delete products'),)},
        ),
        migrations.AlterModelOptions(
            name='productamount',
            options={'permissions': (('mrp_user', 'Can modify, add, view, or delete product amounts'),)},
        ),
        migrations.AlterModelOptions(
            name='productlocation',
            options={'permissions': (('modify_admin_site', 'Can modify, add, view, or delete product locations'),)},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': (('mrp_user', 'Can modify, add, view, or delete purchase orders'),)},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderparts',
            options={'permissions': (('mrp_user', 'Can modify, add, view, or delete purchase order parts'),)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'permissions': (('mrp_user', 'Can modify, add, view, or delete types'),)},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': (('mrp_user', 'Can modify, add, view, or delete vendors'),)},
        ),
    ]
