# Generated by Django 2.1.2 on 2019-05-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0084_auto_20190513_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'permissions': (('mrp_user', 'Can modify, add, view, or delete locations'),),
            },
        ),
        migrations.CreateModel(
            name='Location1Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part')),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or location relationships'),),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer1Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(blank=True, max_length=40)),
                ('manufacturer', models.ForeignKey(limit_choices_to={'vendor_type': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Vendor')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_system.Part')),
            ],
            options={
                'permissions': (('modify_admin_site', 'Can modify, add, view, or delete manufacturer relationships'),),
            },
        ),
    ]
