# Generated by Django 2.1.2 on 2019-05-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0085_location1_location1relationship_manufacturer1relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digikeyapi',
            options={'permissions': (('mrp_admin', 'Can modify, add, view, or delete digikeyapis'),)},
        ),
    ]
