# Generated by Django 2.1.2 on 2019-06-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0086_auto_20190531_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location1',
            new_name='MrpSystem',
        ),
        migrations.RemoveField(
            model_name='location1relationship',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location1relationship',
            name='part',
        ),
        migrations.RemoveField(
            model_name='manufacturer1relationship',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='manufacturer1relationship',
            name='part',
        ),
        migrations.AlterModelOptions(
            name='mrpsystem',
            options={'permissions': (('mrp_user', 'Can access mrp site'), ('modify_admin_site', 'Can access admin site, do redirects'), ('time_user', 'Can clock in and out and handle todos'), ('time_supervisor', 'Can manage projects'), ('mrp_admin', 'Can view, add, modify, or delete digikeys'))},
        ),
        migrations.DeleteModel(
            name='Location1Relationship',
        ),
        migrations.DeleteModel(
            name='Manufacturer1Relationship',
        ),
    ]
