# Generated by Django 2.1.2 on 2019-06-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0087_auto_20190601_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digikeyapi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='locationrelationship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacturerrelationship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacturingorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productamount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productlocation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderparts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={},
        ),
    ]
