# Generated by Django 2.1.2 on 2019-06-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0088_auto_20190601_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrpsystem',
            options={'default_permissions': (), 'permissions': (('mrp_user', 'Can access mrp site'), ('modify_admin_site', 'Can access admin site, do redirects'), ('time_user', 'Can clock in and out and handle todos'), ('time_supervisor', 'Can manage projects'), ('mrp_admin', 'Can view, add, modify, or delete digikeys'))},
        ),
    ]
