# Generated by Django 2.1.2 on 2019-07-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_system', '0091_auto_20190701_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='char1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
