export const RETRIEVE_PARTS = "RETRIEVE_PARTS"

// Add Part
export const ADD_PART_START = "ADD_PART_START"
export const ADD_PART_SUCCESS = "ADD_PART_SUCCESS"
export const ADD_PART_FAILURE = "ADD_PART_FAILURE"

// Update Part
export const UPDATE_PART_START = "UPDATE_PART_START"
export const UPDATE_PART_SUCCESS = "UPDATE_PART_SUCCESS"
export const UPDATE_PART_FAILURE = "UPDATE_PART_FAILURE"

// Search Parts
export const SEARCH_START = "SEARCH_START"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_FAILURE = "SEARCH_FAILURE"

// Delete Part
export const DELETE_START = "DELETE_START"
export const DELETE_SUCCESS = "DELETE_SUCCESS"
export const DELETE_FAILURE = "DELETE_FAILURE"