# Generated by Django 2.1.2 on 2019-05-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ('old_path',), 'permissions': (('redirect_user', 'Can enter in a redirect for the user'),), 'verbose_name': 'redirect', 'verbose_name_plural': 'redirects'},
        ),
    ]
