# Generated by Django 2.1.2 on 2019-06-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0002_auto_20190513_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'default_permissions': (), 'ordering': ('old_path',), 'verbose_name': 'redirect', 'verbose_name_plural': 'redirects'},
        ),
    ]
