# Generated by Django 2.1.2 on 2020-10-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='health_insurance',
            field=models.IntegerField(default=0),
        ),
    ]
