# Generated by Django 2.1.2 on 2020-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activities',
            field=models.CharField(default='N/A', max_length=350),
        ),
    ]
