# Generated by Django 2.1.2 on 2019-05-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_profile_payroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'permissions': (('time_supervisor', 'Can view, add, delete, modify projects'),)},
        ),
    ]
