# Generated by Django 2.1.2 on 2020-10-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_profile_health_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payroll_name',
            field=models.CharField(blank=True, default='blahblahblah', max_length=20),
        ),
    ]
