# Generated by Django 2.1.2 on 2019-05-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190513_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('modify_admin_site', 'Can modify, add, view, or delete profiles'),)},
        ),
        migrations.AlterModelOptions(
            name='projectrelationship',
            options={'permissions': (('time_supervisor', 'Can modify, add, view, or delete project relationships'),)},
        ),
    ]
