# Generated by Django 2.1.2 on 2020-10-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_profile_payroll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='health_insurance',
            field=models.FloatField(default=0),
        ),
    ]
