# Generated by Django 2.1.2 on 2019-06-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190531_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='projectrelationship',
            options={},
        ),
    ]
