# Generated by Django 2.1.2 on 2019-06-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20190601_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='projectrelationship',
            options={'default_permissions': ()},
        ),
    ]
