# Generated by Django 2.1.2 on 2020-10-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20201027_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='health_insurance',
        ),
    ]
