# Generated by Django 2.1.2 on 2020-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_profile_health_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='health_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
