# Generated by Django 2.1.2 on 2020-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20201027_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hourly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='salaried',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='health_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
